// <auto-generated />
using System;
using CourseService.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseService.Persistence.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    partial class CourseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseService.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Courseid"));

                    b.Property<string>("Coursecode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Coursename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semesterid")
                        .HasColumnType("integer");

                    b.HasKey("Courseid");

                    b.HasIndex("Semesterid");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("CourseService.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Enrollmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Enrollmentid"));

                    b.Property<int>("Courseid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Enrolldate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer");

                    b.HasKey("Enrollmentid");

                    b.HasIndex("Courseid");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("CourseService.Domain.Entities.Semester", b =>
                {
                    b.Property<int>("Semesterid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Semesterid"));

                    b.Property<DateTime>("Enddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Semestername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Startdate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Semesterid");

                    b.ToTable("Semesters", (string)null);
                });

            modelBuilder.Entity("CourseService.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Subjectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Subjectid"));

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<string>("Subjectcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subjectname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Subjectid");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("CourseService.Domain.Entities.Course", b =>
                {
                    b.HasOne("CourseService.Domain.Entities.Semester", "Semester")
                        .WithMany("Courses")
                        .HasForeignKey("Semesterid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("CourseService.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("CourseService.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseService.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CourseService.Domain.Entities.Semester", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
